# Generated by Django 6.0.3 on 2026-04-17 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
